#!/usr/bin/env bash

# Load ARC path
source ~/.adrc

# Fix paths
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"

# Manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR="vim"
export VISUAL="$EDITOR"

# Set tab title to show only current directory and not full path
export PROMPT_COMMAND='echo -ne "\033];${PWD##*/}\007"; ':"$PROMPT_COMMAND"

# Set custom prompt (using Bash-it helpers)
source "$ARC/lib/bash-it/themes/colors.theme.bash"
source "$ARC/lib/bash-it/themes/base.theme.bash"
SCM_THEME_PROMPT_PREFIX="${cyan}(${green}"
SCM_THEME_PROMPT_SUFFIX="${cyan})"
SCM_THEME_PROMPT_DIRTY=" ${red}✗"
SCM_THEME_PROMPT_CLEAN=" ${green}✓"

function prompt_command() {
  PS1="\n${purple}\h ${reset_color}in ${green}\w\n${green}$(scm_prompt_info) ${green}λ${reset_color} "
}

safe_append_prompt_command prompt_command

# Init fasd with cache to speed up startup
source "$ARC/lib/fasd/fasd" > /dev/null
fasd_cache="$ARC/user/.fasd-init-bash"
if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
  fasd --init posix-alias bash-hook bash-ccomp bash-ccomp-install >| "$fasd_cache"
fi
source "$fasd_cache"
unset fasd_cache

# Load rest of libraries
command -v thefuck >/dev/null 2>&1 eval "$(thefuck --alias)"
command -v hub >/dev/null 2>&1 eval "$(hub alias -s)"

# Finish installation if not installed
if [ ! -d "$ARC/user/installed/" ]; then
  vim +PlugInstall +qall
  mkdir -p "$ARC/user/installed/"
fi

# Fast edit rc files
arc() {
  eval "$EDITOR $ARC/user/$1"
}

# Awesome Star Wars alias
alias starwars="telnet towel.blinkenlights.nl"

# Load user config
[[ -f "$ARC/user/bashrc" ]] &&
  source "$ARC/user/bashrc"

# Load fzf last to override possible bash-completion
source ~/.fzf.bash
