#!/usr/bin/env bash

# Load base .profile (in some environments, if .bash_profile is being loaded, .profile loading is skipped, we do not want that)
if [ -f ~/.profile ]; then
  source ~/.profile
fi

# Load .bashrc (in some environments, .bashrc is not loaded when running login shell, so fix it)
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
