#!/usr/bin/env bash

. ~/.dotconfig

export PANEL_FIFO=/tmp/panel-fifo
export PANEL_HEIGHT=24
export PANEL_FONT="-*-fixed-*-*-*-*-10-*-*-*-*-*-*-*"
export PANEL_WM_NAME=bspwm_panel

bspc monitor VGA-1 -d 1 2 3 4
bspc monitor VGA-2 -d 5 6 7 8

bspc config normal_border_color  "#282828"
bspc config active_border_color  "#dc9656"
bspc config focused_border_color "#7cafc2"
bspc config border_width         5
bspc config window_gap           15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a fzf-menu state=floating

$DOTHOME/lib/linux/wallpaper.sh
st &
mopidy &
polybar left &
polybar right &
xsetroot -cursor_name left_ptr
sxhkd &
~/.eclim/eclipse/eclimd &
compton -b
