quitOnTopLevelReturn: true

gui:
  border: single
  scrollOffMargin: 8

git:
  commit:
    signOff: true

# git:
#   paging:
#     externalDiffCommand: difft --color=always --display=inline --syntax-highlight=on --tab-width=2
