#!/bin/sh
export PANEL_WM_NAME="lemonbar-panel"
if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

p="$(dirname $(realpath $0))"

export COLOR_BG="#073642"
export COLOR_FG="#93A1A1"
export COLOR_ACTIVE="#268BD2"
export COLOR_INACTIVE="#002B36"
export COLOR_DANGER="#DC322F"

function bat {
    local v="$($p/bat.sh)"
    if [ -n "$v" ]; then
        echo " $v%"
    fi
}

function cpu {
    local v="$($p/cpu.sh)"
    if [ -n "$v" ]; then
        echo " $v%"
    fi
}

function mem {
    local v="$($p/mem.sh)"
    if [ -n "$v" ]; then
        echo " $v%"
    fi
}

function gpu {
    local v="$($p/gpu.sh)"
    if [ -n "$v" ]; then
        echo " $v%"
    fi
}

function vol {
    local v="$($p/vol.sh)"
    if [ -n "$v" ]; then
        echo " $v%"
    fi
}

function bright {
    local v="$($p/bright.sh)"
    if [ -n "$v" ]; then
        echo " $v%"
    fi
}

function clock {
    local v="$($p/clock.sh)"
    if [ -n "$v" ]; then
        echo " $v"
    fi
}

function wired {
    local v="$($p/wired.sh)"
    if [ -n "$v" ]; then
        echo " $v"
    fi
}

function wifi {
    local v="$($p/wifi.sh)"
    if [ -n "$v" ]; then
        echo " $v"
    fi
}

function bspwm {
    local v="$($p/bspwm.sh)"
    if [ -n "$v" ]; then
        echo "$v"
    fi
}

# Create fifo
PANEL_FIFO=/tmp/panel-fifo
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
while true; do
    echo "\n" > "$PANEL_FIFO"
    sleep 1
done &

# Subscribe to updates
clock -s > "$PANEL_FIFO" &
pactl subscribe | grep --line-buffered "sink" > "$PANEL_FIFO" &
xtitle -s > "$PANEL_FIFO" &
bspc subscribe report > "$PANEL_FIFO" &

# Get screen width
WIDTH=$(xdpyinfo | awk '/dimensions:/ {print $2}' | cut -d'x' -f1)
while read -r line; do
    echo "%{l}$(bspwm) %{r}$(wired) $(wifi) $(cpu) $(mem) $(gpu) $(vol) $(bright) $(bat) $(clock) "
done < "$PANEL_FIFO" | lemonbar -n "$PANEL_WM_NAME" -f 'Terminess Nerd Font:size=12' -B $COLOR_BG -F $COLOR_FG -g ${WIDTH}x${BAR_HEIGHT}+0+0 &

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"
wait
