#!/usr/bin/env bash

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  bspc monitor $m -d 1 2 3 4 5 6 7 8 9
done

bspc config normal_border_color  "#657B83"
bspc config active_border_color  "#657B83"
bspc config focused_border_color "#268bd2"
bspc config border_width         1
bspc config window_gap           0

# Split ratio
bspc config split_ratio          0.52

# Monocle settings
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

# Focus follows mouse
bspc config focus_follows_pointer true

# Move stuff with mouse
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner

# Menu
screenwidth=$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -d x -f 1)
screenheight=$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -d x -f 2)
winheight=350
if [[ -n $SCALE_FACTOR ]]; then
    winheight=$(echo "$winheight * $SCALE_FACTOR" | bc)
    winheight=${winheight%.*}
fi

offsety="$((screenheight - $winheight))"
bspc rule -a \*:shellmenu state=floating sticky=on border=off rectangle="$screenwidth"x"$winheight"+0+"$offsety"

wid=$(xdo id -m -a "yambar")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"
