#!/usr/bin/env bash

for m in $(polybar --list-monitors | cut -d":" -f1); do
  bspc monitor $m -d 1 2 3 4 5 6
done

bspc config normal_border_color  "#073642"
bspc config active_border_color  "#073642"
bspc config focused_border_color "#268bd2"
bspc config border_width         1
bspc config window_gap           0

# Split ratio
bspc config split_ratio          0.52

# Preserve border and gap settings
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Focus follows mouse
bspc config focus_follows_pointer true

# Menu
screenwidth=$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -d x -f 1)
screenwidth="$((screenwidth - 2))"
winheight=350
bspc rule -a \*:FZFMenu state=floating sticky=on rectangle="$screenwidth"x"$winheight"+0+40

# Start polybar
~/.config/polybar/start.sh
