#!/usr/bin/env bash

bspc monitor VGA-1 -d 1 2 3 4 5 6
bspc monitor VGA-2 -d 7 8 9

bspc config normal_border_color  "#073642"
bspc config active_border_color  "#073642"
bspc config focused_border_color "#268bd2"
bspc config border_width         1
bspc config window_gap           0

# Split ratio
bspc config split_ratio          0.52

# Preserve border and gap settings
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Terminate already running bar instances
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done

# Start polybar
polybar left &
polybar right &
