#!/usr/bin/env bash
shopt -s nullglob globstar

list_clips() {
    cb hs | jq -r '.[].content | if type=="array" then .[].path else if type=="object" then .path else . end end | gsub("\n";"\\\\N")'
}

chosen_line=$(list_clips \
    | ~/.config/dmenu/fzfmenu "$@" \
    --delimiter=: \
    --preview="echo {} | sed 's/\\\\N/\\n/g'" \
    --preview-window=right:40%)

[[ $chosen_line ]] || exit 1
chosen_line=$(echo "$chosen_line" | sed 's/\\N/\n/g')
cb cp "$chosen_line"
