#!/bin/bash

export FZF_DEFAULT_OPTS="\
   --cycle
   --print-query
   --no-multi
   --reverse --no-border --no-info --margin 0%,0%
   --bind tab:down
   --bind btab:up
"

FILE_ARGS=/tmp/FZFMENU_FILE_ARGS
FILE_CHOICES=/tmp/FZFMENU_FILE_CHOICES
TITLE="fzf-menu"

function kill_old() {
  xdotool search --class FZFMenu windowkill
}

scan_args() {
  while IFS= read -r line; do echo "$line"; done
  [ -n "$line" ] && echo "$line"
}

show() {
  while IFS= read -r line; do echo "$line"; done < $FILE_CHOICES;
}

run_menu() {
  kill_old
  scan_args > $FILE_ARGS
  prompt
  show
}

prompt() {
  : > $FILE_CHOICES
  st -c FZFMenu -n FZFMenu -T "$TITLE" \
    -e "$SHELL" -c "
      source ~/.zsh/pack/bundle/start/base16-shell/scripts/base16-$BASE16_THEME_DEFAULT.sh; 
      source ~/.zsh/pack/bundle/start/base16-fzf/bash/base16-$BASE16_THEME_DEFAULT.config;
      ~/.config/dmenu/closeonfocuslost.sh &
      fzf $PROMPT $QUERY < $FILE_ARGS | tail -1 >! $FILE_CHOICES" 2> /dev/null
  [ -s "$FILE_CHOICES" ] || exit 1
}

main() {
  while :; do
    case $1 in
      -l) shift ;;
      -p) shift && TITLE="$TITLE: $1" && PROMPT="--prompt \"$1 > \"" ;;
      -q) shift && QUERY="-q \"$1\"" ;;
      *) break ;;
    esac
    shift
  done
  run_menu
}

main "$@"
