#!/usr/bin/env bash

ps -eo %cpu,%mem,pid,user,args h | \
    sort -k 1 -r | \
    ~/.config/dmenu/fzfmenu "$@" -h "CPU% MEM% PID     USER     ARGS" | \
    awk '{print $3}' | \
    xargs kill -9 &>/dev/null
