#!/usr/bin/env bash

selected_game=$(for file in ~/.steam/steam/steamapps/*.acf; do
    echo "$(grep -oP '"appid"\s+"\K\d+' "$file"): $(grep -oP '"name"\s+"\K[^"]+' "$file")"
done | ~/.config/dmenu/fzfmenu "$@")

appid=$(echo "$selected_game" | grep -oP '^\d+')

if [ -n "$appid" ]; then
    steam -silent -applaunch "$appid"
fi
