#!/bin/sh
scriptpath=$(dirname "$(readlink -f "$0")")

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS
   --color=border:#268bd2
   --border=top
   --margin 0,0
   --preview-window=border-sharp:wrap
   --no-separator
   --info=inline-right
   --cycle
   --print-query
   --no-multi
   --reverse
   --no-separator
   --info=inline-right
"

FILE_ARGS=/tmp/FZFMENU_FILE_ARGS
FILE_CHOICES=/tmp/FZFMENU_FILE_CHOICES
TITLE="fzf-menu"
TERM_CLASS="--class"
if [ "$TERMINAL" = "st" ]; then
   TERM_CLASS="-n"
fi

kill_old() {
  pgrep -x fzfmenu | grep -v "^$$\$" | xargs kill > /dev/null 2>&1
}

scan_args() {
  while IFS= read -r line; do echo "$line"; done
  [ -n "$line" ] && echo "$line"
}

show() {
  while IFS= read -r line; do echo "$line"; done < $FILE_CHOICES;
}

run_menu() {
  kill_old
  scan_args > $FILE_ARGS
  prompt "$@"
  show
}

prompt() {
  : > $FILE_CHOICES
  $TERMINAL $TERM_CLASS FZFMenu -T "$TITLE" \
    -e "$SHELL" -c "
      source ~/.fzf.zsh
      source ~/.zsh/pack/bundle/start/base16-shell/scripts/base16-$BASE16_THEME_DEFAULT.sh;
      source ~/.zsh/pack/bundle/start/base16-fzf/bash/base16-$BASE16_THEME_DEFAULT.config;
      export BAT_THEME=base16-256;

      if [ \"\$XDG_SESSION_TYPE\" != \"wayland\" ]; then
          {
            local window_id=\$(xdotool getwindowfocus)
            while [ \"\$(xdotool getwindowfocus)\" = \"\$window_id\" ]; do
                sleep 0.1
            done
            xdotool windowkill \$window_id
          } &
      fi

      fzf $PROMPT $QUERY $@ < $FILE_ARGS | tail -1 >! $FILE_CHOICES" 2> /dev/null &
  pid=$!
  trap "kill -9 $pid" SIGTERM
  wait $pid
  [ -s "$FILE_CHOICES" ] || exit 1
}

main() {
  while :; do
    case $1 in
      -l) shift ;;
      -p) shift && TITLE="$TITLE: $1" && PROMPT="--prompt \"$1 > \"" ;;
      -q) shift && QUERY="-q \"$1\"" ;;
      *) break ;;
    esac
    shift
  done
  quoted_args=""
  if [ $# -gt 0 ]; then
    quoted_args="$(printf "%q " "$@")"
  fi
  run_menu "$quoted_args"
}

main "$@"
