#!/usr/bin/env bash
shopt -s nullglob globstar
scriptpath=$(dirname "$(readlink -f "$0")")

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | $scriptpath/fzfmenu "$@")

[[ -n $password ]] || exit

if [[ "$password" == OTP/* ]]; then
    exec pass otp -c "$password"
else
    exec pass show -c "$password"
fi
