#!/usr/bin/env bash
shopt -s nullglob globstar
scriptpath=$(dirname "$(readlink -f "$0")")

exec sh <(
    echo -n "$PATH" \
        | xargs -d: -I{} -r -- find -L {} -maxdepth 1 -mindepth 1 -type f -executable -printf '%P\n' 2>/dev/null \
        | sort -u \
        | $scriptpath/fzfmenu "$@" \
        --preview="which {}" \
        --preview-window=down,1
)
