#!/bin/sh
shopt -s nullglob globstar
scriptpath=$(dirname "$(readlink -f "$0")")

selected_game=$(for file in ~/.steam/steam/steamapps/*.acf; do
    echo "$(grep -oP '"appid"\s+"\K\d+' "$file"): $(grep -oP '"name"\s+"\K[^"]+' "$file")"
done | $scriptpath/fzfmenu "$@")

appid=$(echo "$selected_game" | grep -oP '^\d+')

if [ -n "$appid" ]; then
    exec steam -silent -applaunch "$appid"
fi
