# Load bash-it with some sane defaults
export BASH_IT="$ARC_LIB/bashit"

[[ -f "$ARC_USER/bashitrc" ]] &&
  source "$ARC_USER/bashitrc"

[[ -z "$BASH_IT_THEME" ]] &&
  export BASH_IT_THEME='minimal'
[[ -z "$SCM_CHECK" ]] &&
  export SCM_CHECK=true

source "$BASH_IT/bash_it.sh"

# Load libraries
source "$ARC_LIB/qfc/bin/qfc.sh"
source "$ARC_LIB/z/z.sh"

# Load The Fuck if present
command -v thefuck >/dev/null 2>&1 &&
  eval "$(thefuck --alias)"

# Fix paths
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$ARC_LIB/qfc/bin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"

# Manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR="vim"
export VISUAL="$EDITOR"

# Fast edit rc files
rc() {
  eval "$EDITOR $ARC_USER/$1rc"
}

# Awesome Star Wars alias
alias starwars="telnet towel.blinkenlights.nl"