# Load z.sh
[[ -s $ARC_LIB/z/z.sh ]] &&
  source ~/.awesomedotrc/.lib/z/z.sh

# Fix paths
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"

# Manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR="vim"
export VISUAL="$EDITOR"

# Aliases to config files
alias config-bash="$EDITOR $ARC_USER/zshrc"
alias config-vim="$EDITOR $ARC_USER/vimrc"
alias config-plug="$EDITOR $ARC_USER/plug.vim"

# Awesome Star Wars alias
alias star-wars="telnet towel.blinkenlights.nl"

# Awesome Star Wars MOTD
motd[1]=$(echo "$USER, I am your father." | cowsay -f vader-koala)
motd[2]=$(echo "$USER told me enough! $USER told me you killed him!" | cowsay -f luke-koala)
rand=$[$RANDOM % 2 + 1]
echo -e "\033[33m${motd[$rand]}\033[0m"
echo -e "\nRun \033[33mstar-wars\033[0m to watch some Star Wars!"
