#!/usr/bin/env bash

bspc monitor VGA-1 -d 1 2 3 4
bspc monitor VGA-2 -d 5 6 7 8

bspc config normal_border_color  "#2b303b"
bspc config active_border_color  "#96b5b4"
bspc config focused_border_color "#a3be8c"
bspc config border_width         2
bspc config window_gap           15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Terminate already running bar instances
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done

# Start polybar
polybar left &
polybar right &
