#!/bin/bash

export CHUNKC_SOCKET=4131

# Tiling
chunkc config global_space_mode bsp
chunkc config global_space_offset_top      25
chunkc config global_space_offset_bottom   0
chunkc config global_space_offset_left     0
chunkc config global_space_offset_right    0
chunkc config global_space_offset_gap      0

chunkc config bsp_spawn_left                1
chunkc config bsp_optimal_ratio         1.618
chunkc config bsp_split_mode          optimal
chunkc config bsp_split_ratio             0.5

chunkc config mouse_follows_focus           0
chunkc config window_float_next             0

# signal dock to make windows topmost when floated
# requires chwm-sa (https://github.com/koekeishiya/chwm-sa)
chunkc config window_float_topmost 0
