#!/bin/bash

# Tiling
export CHUNKC_SOCKET=4131
chunkc config global_desktop_mode bsp
chunkc config global_desktop_offset_top    0
chunkc config global_desktop_offset_bottom 0
chunkc config global_desktop_offset_left   0
chunkc config global_desktop_offset_right  0
chunkc config global_desktop_offset_gap    0
chunkc config bsp_spawn_left               1
chunkc config bsp_optimal_ratio            1.618
chunkc config bsp_split_mode               optimal
chunkc config bsp_split_ratio              0.5
chunkc config mouse_follows_focus          0
chunkc config window_focus_cycle           none
chunkc config window_float_next            0
chunkc config window_float_topmost         0
