#!/bin/zsh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Load profile
source ~/.profile

# Load dotconfig because of $DOTHOME
source ~/.dotconfig

# Set up x stuff first
xsetroot -cursor_name left_ptr
xmodmap ~/.xmodmap

# Now, open terminal window
st &

# Start music manager daemon
mopidy &

# Start dropbox
dropbox start &

# Start guest additions if available
if command -v VBoxClient-all >/dev/null 2>&1; then
  VBoxClient-all
fi

# Set nice wallpaper
$DOTHOME/lib/linux/wallpaper.sh &

# Start clipboard manager daemon
$DOTHOME/lib/linux/clipmenu/clipmenud &

# We want to use old ugly stuff
setopt sh_word_split

# Start key manager daemon
sxhkd &

# And finally, start our WM
exec bspwm
