#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

. ~/.dotconfig

# Set up x stuff first
xrdb -merge ~/.Xresources & 
xsetroot -cursor_name left_ptr

# Now, open terminal window
st &

# Now, run some programs
$DOTHOME/lib/linux/wallpaper.sh
mopidy &
~/.eclim/eclipse/eclimd &
# compton -b

# And finally, start WM
sxhkd &
exec bspwm
