#!/bin/zsh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Load profile
source ~/.profile

# Load dotconfig because of $DOTHOME
source ~/.dotconfig

# Set up x stuff first
xsetroot -cursor_name left_ptr

# Start music manager daemon
mopidy &

# Now, open terminal window
st &

dropbox start &

# Set nice wallpaper
$DOTHOME/lib/linux/wallpaper.sh &

# Start clipboard manager daemon
$DOTHOME/lib/linux/clipmenu/clipmenud &

# Start key manager daemon
sxhkd &

# And finally, start our WM
exec bspwm
