# vim:foldmethod=marker:set ft=zsh:

# General {{{

  # Source .profile
  if [ -f ~/.profile ]; then
    source ~/.profile
  fi

  # Enable colors
  export CLICOLOR=1

# }}}

# Aliases & functions {{{

  # Some aliases and enhancements for homebrew
  if command -v brew >/dev/null 2>&1; then
    export PYTHONPATH=$(brew --prefix)/lib/python2.7/site-packages:$PYTHONPATH
    alias brewup='brew update && brew upgrade --all && brew cleanup && brew cask cleanup'
  fi

  # Alias xclip copy/paste to same as on macOS for consistency
  if command -v xclip >/dev/null 2>&1; then
    alias pbcopy='xclip -i -selection clipboard'
    alias pbpaste='xclip -o -selection clipboard'
  fi

  # Open Java project in Vim with Eclim
  function vjava () {
    $EDITOR --servername "$1" +Session +"ProjectOpen $1"
  }

  # Super cool gource alias (requires gource)
  alias gource="gource --key --stop-at-end -i 0 --highlight-dirs --highlight-all-users --max-file-lag 0.5"

  # Hastebin fast share
  haste() { a=$(cat); curl -X POST -s -d "$a" http://hastebin.com/documents | awk -F '"' '{print "http://hastebin.com/"$4}'; }
# }}}

# Plugins {{{

  # Source zim
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh

  # Load vi mode plugin
  source "$DOTHOME/lib/shell/vi-mode.plugin.zsh"

  # Base 16
  eval "$($DOTHOME/lib/shell/base16-shell/profile_helper.sh)"
  [ -z $BASE16_THEME ] && base16_tomorrow-night

  # Load hub alias
  command -v hub >/dev/null 2>&1 && eval "$(hub alias -s)"

  # Load fzf
  source ~/.fzf.zsh

  # Use faster FZF grep command if possible
  if command -v rg >/dev/null 2>&1; then
    export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
  elif command -v ag >/dev/null 2>&1; then
    export FZF_DEFAULT_COMMAND='ag -g ""'
  fi

# }}}

# User configuration {{{

  # Load user config
  [[ -f "$DOTHOME/usr/zshrc" ]] &&
    source "$DOTHOME/usr/zshrc"

# }}}
