# vim:foldmethod=marker:set ft=zsh:

# General {{{

  # Source .profile
  if [ -f ~/.profile ]; then
    source ~/.profile
  fi

  # Enable colors
  export CLICOLOR=1

  setopt sh_word_split

# }}}

# Aliases & functions {{{

  # Switch to neovim
  alias vim='nvim'

  # Update and cleanup homebrew
  if command -v brew >/dev/null 2>&1; then
    alias brewup='brew update && brew upgrade && brew cleanup && brew cask cleanup'
  fi

  # Alias xclip copy/paste to same as on macOS for consistency
  if command -v xclip >/dev/null 2>&1; then
    alias pbcopy='xclip -i -selection clipboard'
    alias pbpaste='xclip -o -selection clipboard'
  fi

  # Open Vim and start saving it's session
  function vsession () {
    $EDITOR +Session
  }

  # Super cool gource alias (requires gource)
  alias gource="gource --key --stop-at-end -i 0 --highlight-dirs --highlight-all-users --max-file-lag 0.5"

  # Hastebin fast share
  haste() { a=$(cat); curl -X POST -s -d "$a" https://hastebin.com/documents | awk -F '"' '{print "https://hastebin.com/"$4}'; }

# }}}

# Plugins {{{

  # Source zim
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh

  # Load tmux plugin
  export ZSH_TMUX_AUTOSTART=true
  export ZSH_TMUX_FIXTERM=false
  export ZSH_TMUX_AUTOCONNECT=true
  source "$DOTHOME/lib/shell/tmux.plugin.zsh"

  # Load vi mode plugin
  source "$DOTHOME/lib/shell/vi-mode.plugin.zsh"

  # Base 16
  eval "$($DOTHOME/lib/shell/base16-shell/profile_helper.sh)"
  [ -z $BASE16_THEME ] && base16_solarized-dark

  # Load hub alias
  command -v hub >/dev/null 2>&1 && eval "$(hub alias -s)"

  # Load fzf
  source ~/.fzf.zsh

  # Use faster FZF grep command if possible
  if command -v rg >/dev/null 2>&1; then
    export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
  elif command -v ag >/dev/null 2>&1; then
    export FZF_DEFAULT_COMMAND='ag -g ""'
  fi

# }}}

# User configuration {{{

  # Load user config
  [[ -f "$DOTHOME/usr/zshrc" ]] &&
    source "$DOTHOME/usr/zshrc"

# }}}
