[general]
fullscreen = true
early-exit = true
corner-roundness = 0
initial-tool = "crop"
copy-command = "wl-copy"
annotation-size-factor = 2
output-filename = "~/Pictures/Screenshots/%Y-%m-%d_%H:%M:%S.png"
action-on-enter = "save-to-clipboard"
save-after-copy = true
default-hide-toolbars = false
primary-highlighter = "block"
disable-notifications = false
