#!/bin/bash

# Copy config files
echo "Copying config files..."
cp zshrc ~/.zshrc
cp vimrc ~/.vimrc
cp zpreztorc ~/.zpreztorc

# Use same configuration for NeoVim and Vim
echo "Adjusting NeoVim configuration..."
rm -rf ~/.config/nvim
mkdir -p ~/.config/nvim
ln -s ~/.vim/autoload ~/.config/nvim/autoload
ln -s ~/.vimrc ~/.config/nvim/init.vim

echo "Installation done. Vim cheatsheet: http://vim.rtorr.com"
[[ ! $TERM == "dumb" ]] && zsh
