#!/bin/bash

cp ~/.zshrc zshrc && echo 'zsh config updated succesfully'
cp ~/.zpreztorc zpreztorc && echo 'zprezto config updated succesfully'
cp ~/.vimrc vimrc && echo 'vim config updated succesfully'
