color_bg: &color_bg 002B36ff
# color_bg: &color_bg 002B3640
color_fg: &color_fg 93A1A1ff
color_fg_inv: &color_fg_inv 002B36ff
color_success: &color_success 859900ff
color_active: &color_active 268BD2ff
color_inactive: &color_inactive 073642FF
color_urgent: &color_urgent CB4B16ff
color_warning: &color_warning B58900ff
margin: &margin 15

bar:
  location: top
  font: monospace:size=${BAR_FONT_SIZE}
  height: ${BAR_HEIGHT}
  foreground: *color_fg
  background: *color_bg

  left:
    -
      script:
        path: ~/.config/yambar/wm.sh
        content:
          map:
            conditions:
              monitor != "":
                list:
                  spacing: 0
                  items:
                    # - string: {text: "{monitor}", margin: *margin}
                    - map:
                        conditions:
                          mode != DEFAULT:
                            string: {text: "-- {mode} --", foreground: *color_success, margin: *margin}
                    - map:
                        conditions:
                          fullscreen:
                            string: {text: " ", foreground: *color_fg_inv, deco: {background: {color: *color_active}}, margin: *margin}
                          floating:
                            string: {text: " ", foreground: *color_fg_inv, deco: {background: {color: *color_active}}, margin: *margin}
                          monocle:
                            string: {text: " ", foreground: *color_fg_inv, deco: {background: {color: *color_active}}, margin: *margin}
                          ~monocle:
                            string: {text: " ", foreground: *color_fg_inv, deco: {background: {color: *color_active}}, margin: *margin}
                    - map:
                        conditions:
                          process != "" && xwayland:
                            string: {text: "{process}", foreground: *color_fg_inv, deco: {background: {color: *color_warning}}, margin: *margin}
                          process != "":
                            string: {text: "{process}", deco: {background: {color: *color_inactive}}, margin: *margin}
                    - map:
                        conditions:
                          title != "":
                            string: {text: "{title}", max: 90, margin: *margin}
  right:
    -
      network:
        poll-interval: 5000
        content:
          map:
            conditions:
              type == wlan && state == up:
                string: {text: "  {ssid}", margin: *margin}
              type == ethernet && state == up:
                string: {text: "  {ipv4}", margin: *margin}
    -
      mem:
        content:
          map:
            conditions:
              percent_used >= 80:
                string: {text: "  {percent_used}%", foreground: *color_urgent, margin: *margin}
              percent_used >= 65:
                string: {text: "  {percent_used}%", foreground: *color_warning, margin: *margin}
              percent_used >= 0:
                string: {text: "  {percent_used}%", margin: *margin}
    -
      script:
        path: ~/.config/yambar/cpu.sh
        poll-interval: 2000
        content:
          map:
            conditions:
              utilization >= 80 || temperature >= 80:
                string: {text: "  {utilization}%|{temperature}°C", foreground: *color_urgent, margin: *margin}
              utilization >= 65 || temperature >= 65:
                string: {text: "  {utilization}%|{temperature}°C", foreground: *color_warning, margin: *margin}
              utilization >= 0:
                string: {text: "  {utilization}%|{temperature}°C", margin: *margin}
    -
      script:
        path: ~/.config/yambar/gpu.sh
        content:
          map:
            conditions:
              utilization >= 80 || temperature >= 80:
                string: {text: "  {utilization}%|{temperature}°C", foreground: *color_urgent, margin: *margin}
              utilization >= 65 || temperature >= 65:
                string: {text: "  {utilization}%|{temperature}°C", foreground: *color_warning, margin: *margin}
              utilization >= 0:
                string: {text: "  {utilization}%|{temperature}°C", margin: *margin}
    -
      alsa:
        card: hw:PCH
        mixer: Master
        content:
          map:
            conditions:
              muted:
                string: {text: " ", foreground: *color_urgent, margin: *margin}
              ~muted:
                string: {text: "  {percent}%", margin: *margin}
    -
      alsa:
        card: hw:PCH
        mixer: Capture
        content:
          map:
            conditions:
              muted:
                string: {text: " ", foreground: *color_urgent, margin: *margin}
              ~muted:
                string: {text: " {percent}%", margin: *margin}
    -
      script:
        path: ~/.config/yambar/brightness.sh
        poll-interval: 1000
        content:
          string: {text: " {brightness}%", margin: *margin}
    -
      battery:
        name: BAT0
        content:
          map:
            conditions:
              capacity <= 10:
                string: {text: "  {capacity}%", foreground: *color_urgent, margin: *margin}
              capacity <= 30:
                string: {text: "  {capacity}%", foreground: *color_warning, margin: *margin}
              capacity <= 100:
                string: {text: "  {capacity}%", margin: *margin}
    -
      clock:
        date-format: "%Y-%m-%d"
        time-format: "%H:%M"
        content:
          string: {text: "  {date} {time}", margin: *margin}
    -
      script:
        path: ~/.config/yambar/notifications.sh
        poll-interval: 600000
        content:
          list:
            spacing: 0
            items:
              - map:
                  conditions:
                    updates > 0:
                      string: {text: "  {updates}", foreground: *color_urgent, margin: *margin}
              - map:
                  conditions:
                    github > 0:
                      string: {text: "  {github}", foreground: *color_active, margin: *margin}
