color_bg: &color_bg 073642ff
color_fg: &color_fg 93A1A1ff
color_active: &color_active 268BD2ff
color_inactive: &color_inactive 002B36ff
color_urgent: &color_urgent DC322Fff
color_warning: &color_warning B58900ff
margin: &margin 15

bar:
  location: top
  font: monospace:size=32
  height: 60
  foreground: *color_fg
  background: *color_bg

  left:
    -
      script:
        path: ~/.config/yambar/wm.sh
        content:
          map:
            default:
              string: {text: " ", foreground: *color_bg, deco: {background: {color: *color_active}}, margin: *margin}
            conditions:
              monitor != "":
                list:
                  spacing: 0
                  items:
                    - string: {text: "{monitor}", margin: *margin}
                    - map:
                        conditions:
                          fullscreen:
                            string: {text: " ", deco: {background: {color: *color_inactive}}, margin: *margin}
                          floating:
                            string: {text: " ", deco: {background: {color: *color_inactive}}, margin: *margin}
                          monocle:
                            string: {text: " ", deco: {background: {color: *color_inactive}}, margin: *margin}
                          ~monocle:
                            string: {text: " ", deco: {background: {color: *color_inactive}}, margin: *margin}
                    - map:
                        conditions:
                          ws1_state == occupied:
                            string: {text: 1, margin: *margin}
                          ws1_state == empty:
                            string: {text: 1, deco: {background: {color: *color_inactive}}, margin: *margin}
                          ws1_state == urgent:
                            string: {text: 1, foreground: *color_bg, deco: {background: {color: *color_urgent}}, margin: *margin}
                          ws1_state == focused:
                            string: {text: 1, foreground: *color_bg, deco: {background: {color: *color_active}}, margin: *margin}
                    - map:
                        conditions:
                          ws2_state == occupied:
                            string: {text: 2, margin: *margin}
                          ws2_state == empty:
                            string: {text: 2, deco: {background: {color: *color_inactive}}, margin: *margin}
                          ws2_state == urgent:
                            string: {text: 2, foreground: *color_bg, deco: {background: {color: *color_urgent}}, margin: *margin}
                          ws2_state == focused:
                            string: {text: 2, foreground: *color_bg, deco: {background: {color: *color_active}}, margin: *margin}
                    - map:
                        conditions:
                          ws3_state == occupied:
                            string: {text: 3, margin: *margin}
                          ws3_state == empty:
                            string: {text: 3, deco: {background: {color: *color_inactive}}, margin: *margin}
                          ws3_state == urgent:
                            string: {text: 3, foreground: *color_bg, deco: {background: {color: *color_urgent}}, margin: *margin}
                          ws3_state == focused:
                            string: {text: 3, foreground: *color_bg, deco: {background: {color: *color_active}}, margin: *margin}
                    - map:
                        conditions:
                          ws4_state == occupied:
                            string: {text: 4, margin: *margin}
                          ws4_state == empty:
                            string: {text: 4, deco: {background: {color: *color_inactive}}, margin: *margin}
                          ws4_state == urgent:
                            string: {text: 4, foreground: *color_bg, deco: {background: {color: *color_urgent}}, margin: *margin}
                          ws4_state == focused:
                            string: {text: 4, foreground: *color_bg, deco: {background: {color: *color_active}}, margin: *margin}
                    - map:
                        conditions:
                          ws5_state == occupied:
                            string: {text: 5, margin: *margin}
                          ws5_state == empty:
                            string: {text: 5, deco: {background: {color: *color_inactive}}, margin: *margin}
                          ws5_state == urgent:
                            string: {text: 5, foreground: *color_bg, deco: {background: {color: *color_urgent}}, margin: *margin}
                          ws5_state == focused:
                            string: {text: 5, foreground: *color_bg, deco: {background: {color: *color_active}}, margin: *margin}
                    - map:
                        conditions:
                          process != "" && xwayland:
                            string: {text: "{process}", foreground: *color_bg, deco: {background: {color: *color_warning}}, margin: *margin}
                          process != "":
                            string: {text: "{process}", foreground: *color_bg, deco: {background: {color: *color_active}}, margin: *margin}
                    - map:
                        conditions:
                          title != "":
                            string: {text: "{title}", max: 75, margin: *margin}
  right:
    -
      network:
        poll-interval: 1000
        content:
          map:
            conditions:
              name == wlan0:
                string: {text: "  {ssid}", margin: *margin}
    -
      cpu:
        content:
          map:
            conditions:
              id < 0:
                string: {text: "  {cpu}%", margin: *margin}
    -
      mem:
        content:
          string: {text: "  {percent_used}%", margin: *margin}
    -
      script:
        path: ~/.config/yambar/gpu.sh
        content:
          map:
            conditions:
              percent >= 0:
                string: {text: "  {percent}%", margin: 15}
    -
      alsa:
        card: hw:PCH
        mixer: Master
        content:
          string: {text: "  {percent}%", margin: *margin}
    -
      backlight:
        name: nvidia_wmi_ec_backlight
        content:
          string: {text: " {percent}%", margin: *margin}
    -
      battery:
        name: BAT0
        content:
          string: {text: "  {capacity}%", margin: *margin}
    -
      clock:
        date-format: "%Y-%m-%d"
        time-format: "%H:%M"
        content:
          string: {text: "  {date} {time}", margin: *margin}
    -
      script:
        path: ~/.config/yambar/arch.sh
        poll-interval: 900000
        content:
          map:
            conditions:
              updates > 0:
                string: {text: "  {updates}", foreground: *color_bg, deco: {background: {color: *color_urgent}}, margin: *margin}
