color_bg: &color_bg 073642ff
color_fg: &color_fg 93A1A1ff
color_active: &color_active 268BD2ff
color_inactive: &color_inactive 002B36ff
color_urgent: &color_urgent DC322Fff

bar:
  location: top
  font: Terminess Nerd Font:size=26
  height: 60

  foreground: *color_fg
  background: *color_bg

  border:
    width: 0

  left:
    # -
    #   script:
    #     path: ~/.config/yambar/bspwm.sh
    -
      river:
        anchors:
          -
            base: &river_base
              left-margin: 15
              right-margin: 15
              conditions:
                id == 1: {string: {text: 1}}
                id == 2: {string: {text: 2}}
                id == 3: {string: {text: 3}}
                id == 4: {string: {text: 4}}
                id == 5: {string: {text: 5}}
        content:
          map:
            conditions:
              urgent:
                map:
                  <<: *river_base
                  foreground: *color_bg
                  deco: {background: {color: *color_urgent}}
              visible:
                map:
                  <<: *river_base
                  foreground: *color_bg
                  deco: {background: {color: *color_active}}
              occupied:
                map:
                  <<: *river_base
              ~occupied:
                map:
                  <<: *river_base
                  deco: {background: {color: *color_inactive}}
    -
      xwindow:
        content:
          map:
            conditions:
              title != "":
                - string: {text: "{application}", foreground: *color_bg, deco: {background: {color: *color_active}}}
                - string: {text: "{title}"}
    -
      foreign-toplevel:
        content:
          map:
            conditions:
              title != "":
                - string: {text: "{app-id}", foreground: *color_bg, deco: {background: {color: *color_active}}}
                - string: {text: "{title}"}
  right:
    -
      network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlan0:
                - string: {text: "  "}
                - string: {text: "{ssid} {dl-speed:mb}/{ul-speed:mb} Mb/s"}
    -
      alsa:
        card: hw:PCH
        mixer: Master
        content:
          - string: {text: "  "}
          - string: {text: "{percent}%"}
    -
      backlight:
        name: nvidia_wmi_ec_backlight
        content:
          - string: {text: " "}
          - string: {text: "{percent}%"}
    -
      battery:
        name: BAT0
        content:
          - string: {text: "  "}
          - string: {text: "{capacity}%"}
    -
      clock:
        date-format: "%Y-%m-%d"
        time-format: "%H:%M"
        content:
          - string: {text: "  "}
          - string: {text: "{date} {time}"}
