#!/bin/sh

# Super+w to close or kill the current view
riverctl map normal Super W close

# Super+Shift+Escape to quit river
riverctl map normal Super+Shift Escape exit

# Super+{_,Shift+}w to close or kill the current view
riverctl map normal Super W close
riverctl map normal Super+Shift W close

# Super+{_,Shift+}{h,j,k,l} to focus or swap the view in the given direction
riverctl map normal Super H focus-view left
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right
riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift J swap down
riverctl map normal Super+Shift K swap up
riverctl map normal Super+Shift L swap right

# Super+bracket{left,right} to focus the next/previous view
riverctl map normal Super bracketleft focus-view previous
riverctl map normal Super bracketright focus-view next

# Super+brace{left,right} to focus the next/previous output
riverctl map normal Super braceleft focus-output previous
riverctl map normal Super braceright focus-output next

# Super+T to bump the focused view to the top of the layout stack
riverctl map normal Super T zoom

# Super+S to toggle float
riverctl map normal Super S toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Return to open terminal
riverctl map normal Super Return spawn alacritty

# Various media key mapping examples for both normal and locked mode which do not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'amixer -q set Master 5%+ on'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'amixer -q set Master 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'amixer -q set Master toggle'
    riverctl map $mode None XF86AudioMicMute      spawn 'amixer -q set Capture toggle'
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# Set way-displays
way-displays > /tmp/way-displays.${XDG_VTNR}.${USER}.log 2>&1 &

# Start waybar
riverctl spawn waybar
