#!/bin/sh

export LIBVA_DRIVER_NAME=nvidia
export XDG_SESSION_TYPE=wayland
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export GDK_BACKEND=wayland,x11
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
export MOZ_ENABLE_WAYLAND=1
export MOZ_DISABLE_RDD_SANDBOX=1
export QT_QPA_PLATFORM=wayland
export WLR_NO_HARDWARE_CURSORS=1
export __NV_PRIME_RENDER_OFFLOAD=1
export __VK_LAYER_NV_optimus=NVIDIA_only
export PROTON_ENABLE_NGX_UPDATER=1
export NVD_BACKEND=direct
export __GL_GSYNC_ALLOWED=1
export __GL_VRR_ALLOWED=1
export WLR_DRM_NO_ATOMIC=1
export WLR_USE_LIBINPUT=1
export __GL_MaxFramesAllowed=1
export QT_SCALE_FACTOR=1

# Super+w to close or kill the current view
riverctl map normal Super W close

# Super+Shift+Escape to quit river
riverctl map normal Super+Shift Escape exit

# Super+{_,Shift+}w to close or kill the current view
riverctl map normal Super W close
riverctl map normal Super+Shift W close

# Super+{_,Shift+}{h,j,k,l} to focus or swap the view in the given direction
riverctl map normal Super H focus-view left
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right
riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift J swap down
riverctl map normal Super+Shift K swap up
riverctl map normal Super+Shift L swap right

# Super+bracket{left,right} to focus the next/previous view
riverctl map normal Super bracketleft focus-view previous
riverctl map normal Super bracketright focus-view next

# Super+brace{left,right} to focus the next/previous output
riverctl map normal Super braceleft focus-output previous
riverctl map normal Super braceright focus-output next

# Super+T to bump the focused view to the top of the layout stack
riverctl map normal Super T zoom

# Super+S to toggle float
riverctl map normal Super S toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 5)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Various media key mapping examples for both normal and locked mode which do not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'amixer -q set Master 5%+ on'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'amixer -q set Master 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'amixer -q set Master toggle'
    riverctl map $mode None XF86AudioMicMute      spawn 'amixer -q set Capture toggle'
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x268bd2
riverctl border-color-unfocused 0x073642

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &

# Configure scale
wlr-randr --output eDP-2 --scale $SCALE_FACTOR
screenwidth=$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -d x -f 1)
screenwidth="$((screenwidth - 2))"
screenheight=$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -d x -f 2)
screenheight="$((screenheight - 2))"
winheight=$(echo "350 * $SCALE_FACTOR" | bc)
winheight=${winheight%.*}
offsety="$((screenheight - $winheight))"

riverctl rule-add -app-id 'FZFMenu' float
riverctl rule-add -app-id 'FZFMenu' position  0 $offsety
riverctl rule-add -app-id 'FZFMenu' dimensions $screenwidth $winheight

# Application mappings
riverctl map normal Super Return spawn "alacritty -e $SHELL -ic 'tmux new-session -A -s default'"
riverctl map normal Super Tab spawn "~/.config/fzfmenu/windowsmenu -p 'switch'"
riverctl map normal Super space spawn "~/.config/fzfmenu/runmenu -p 'run'"
riverctl map normal Super z spawn "~/.config/fzfmenu/passmenu -p 'pass'"
riverctl map normal Super x spawn "~/.config/fzfmenu/procmenu -p 'proc'"
riverctl map normal Super c spawn "~/.config/fzfmenu/clipmenu -p 'clip'"
riverctl map normal Super v spawn "~/.config/fzfmenu/steammenu -p 'steam'"

riverctl spawn "swaybg -i $HOME/.wallpaper"
riverctl spawn /usr/lib/geoclue-2.0/demos/agent
riverctl spawn dunst
riverctl spawn yambar
riverctl spawn gammastep
riverctl spawn udiskie
riverctl spawn dropbox
riverctl spawn "alacritty -e $SHELL -ic 'tmux new-session -A -s default'"
